//Authentication Actions
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN'
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const ATTEMPT_REGISTER_USER = 'ATTEMPT_REGISTER_USER'

// USER AUTHENTICATION STATES
export const GUEST = 'GUEST'
export const AUTHENTICATED = 'AUTHENTICATED'
export const AWAITING_AUTHENTICATION = 'AWAITING_AUTHENTICATION'
