//Profile Actions
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const UNLOAD_PROFILE = 'UNLOAD_PROFILE'
export const STORE_PROFILE = 'STORE_PROFILE'
export const CREATE_PROFILE_WITH_EMAIL = 'CREATE_PROFILE_WITH_EMAIL'
export const CREATE_PROFILE_WITH_PROVIDER = 'CREATE_PROFILE_WITH_PROVIDER'


// USER PROFILE STATES
export const PROFILE_UPDATED = 'PROFILE_UPDATED'
export const LOADING_PROFILE = 'LOADING_PROFILE'
export const PROFILE_LOADED = 'PROFILE_LOADED'
export const NO_PROFILE = 'NO_PROFILE'
export const PROFILE_UNLOADED = 'PROFILE_UNLOADED'
export const NEW_PROFILE = 'CREATING_PROFILE'

export const FETCH_PROFILE_TIMEOUT = 5000;

